### ISSUE TITLE
Server return 400 error

### ISSUE THREAD

**Issue by M00T1CU5** [Geam/steam_workshop_downloader#1]
I get "Server return 400 error" when trying to download a workshop item on Ubuntu 16.04

Running the command: ./workshop.py 680631864

**Comment by Geam** [comment]
Hi @Mooticus sorry for the late answer.
The reason you get the 400 error is that 680631864 is not a collection but an addon.
As said in the readme of the script:
"
Add only a plugin

No, you can't and I don't want to implement it. Create a collection, your players will thank you if you have more than one plugin. If you only have one plugin, one day you will use many so create a collection.
"

Anyway, the curl command to download your plugin is : 
`curl -0 http://images.akamai.steamusercontent.com/ugc/48734286214157446/89FF0DBC6563745F6CD70EB0FE548A9F265FA641/ > 313949717.vpk`
